"use client";

import { AIMessageComponent } from "@/components/message";

export const AudioLoading = () => (
  <AIMessageComponent>
    <div className="w-96 bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl p-6 border border-purple-200/50 shadow-lg">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-xl  flex items-center justify-center shadow-lg">
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
            </svg>
          </div>
          <div className="space-y-2">
            <div className="h-4 bg-gradient-to-r from-purple-200 to-blue-200 rounded-full animate-pulse w-32"></div>
            <div className="h-3 bg-gradient-to-r from-purple-100 to-blue-100 rounded-full animate-pulse w-24"></div>
          </div>
        </div>
        <div className="w-8 h-8 rounded-full bg-gradient-to-r from-purple-200 to-blue-200 animate-pulse"></div>
      </div>
      
      <div className="space-y-3">
        <div className="h-2 bg-gradient-to-r from-purple-200 to-blue-200 rounded-full animate-pulse"></div>
        <div className="h-2 bg-gradient-to-r from-purple-200 to-blue-200 rounded-full animate-pulse w-3/4"></div>
        <div className="h-2 bg-gradient-to-r from-purple-200 to-blue-200 rounded-full animate-pulse w-1/2"></div>
      </div>
      
      <div className="mt-4 flex items-center justify-between">
        <div className="flex space-x-2">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-r from-purple-200 to-blue-200 animate-pulse"></div>
          <div className="w-8 h-8 rounded-lg bg-gradient-to-r from-purple-200 to-blue-200 animate-pulse"></div>
          <div className="w-8 h-8 rounded-lg bg-gradient-to-r from-purple-200 to-blue-200 animate-pulse"></div>
        </div>
        <div className="h-6 bg-gradient-to-r from-purple-200 to-blue-200 rounded-full animate-pulse w-16"></div>
      </div>
    </div>
  </AIMessageComponent>
);

export const Audio = ({ id }: { id: string }) => (
  <AIMessageComponent>
    <div className="w-96 bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl p-6 border border-purple-200/50 shadow-lg backdrop-blur-sm">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-3">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center shadow-lg">
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
            </svg>
          </div>
          <div>
            <h3 className="font-semibold text-gray-900">Audio Response</h3>
            <p className="text-sm text-gray-600">Generated by AI</p>
          </div>
        </div>
        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center">
          <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
          </svg>
        </div>
      </div>
      
      <div className="bg-white rounded-xl p-4 shadow-inner border border-purple-100">
        <audio 
          controls 
          className="w-full h-12 rounded-lg"
          style={{
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          }}
        >
          <source src={`${id}.mp3`} type="audio/mp3" />
          Your browser does not support the audio element.
        </audio>
      </div>
      
      <div className="mt-4 flex items-center justify-between text-sm text-gray-600">
        <div className="flex items-center space-x-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span>Ready to play</span>
        </div>
        <div className="flex items-center space-x-1">
          <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
          <span>Available</span>
        </div>
      </div>
    </div>
  </AIMessageComponent>
);
